# Generated by Django 4.0.1 on 2022-02-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_review_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='website.jpg', null=True, upload_to='photos/'),
        ),
    ]
