# Generated by Django 4.0.1 on 2022-02-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
